server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.175.135:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      #      url: jdbc:mysql://192.168.0.166:3306/management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      #      url: jdbc:mysql://192.168.2.196:3306/management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: zero
    password: zero
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
    driver-class-name: org.gjt.mm.mysql.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1 # eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
#    lease-expiration-duration-in-seconds: 2 # eureka


mybatis:
  type-aliases-package: com.wangyiran.springcloud.entity #实体类的存放路径，如：com.funtl.hello.spring.boot.entity
  mapper-locations: classpath:mapper/*Mapper.xml